name       : mate-notification-theme-slate
version    : 4
release    : 4
source     :
    - https://github.com/solus-project/mate-notification-theme-slate/releases/download/v4/mate-notification-theme-slate-4.tar.xz : 27d248b1a3c77c4612e413df95af239c30231cc4c1a9de85fca6de861e7134c7
license    : LGPL-2.1
component  : desktop.mate
summary    : The Slate otification Daemon theme for MATE
description: |
    This provides a notification style identical to the Arc-styled Budgie Desktop notifications.
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - mate-notification-daemon
replaces   :
    - mate-notification-theme-solus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Ensure upgrades don't break the existing configuration
    ln -sv libslate.so $installdir/%libdir%/mate-notification-daemon/engines/libsolus-mate-theme.so
