name       : mate-notification-theme-slate
version    : '6.0'
release    : 13
source     :
    - https://github.com/getsolus/mate-notification-theme-slate/releases/download/6.0/mate-notification-theme-slate-6.tar.xz : 56c09047a6f96ff95eeef416d482683aceb4e86f372688b27eb5e322c82f03a4
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : The Slate notification Daemon theme for MATE
description: |
    This provides a notification style identical to the Arc-styled Budgie Desktop notifications.
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - mate-notification-daemon
replaces   :
    - mate-notification-theme-solus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Ensure upgrades don't break the existing configuration
    ln -sv libslate.so $installdir/%libdir%/mate-notification-daemon/engines/libsolus-mate-theme.so
