name       : mate-notification-theme-slate
version    : '5'
release    : 9
source     :
    - https://github.com/solus-project/mate-notification-theme-slate/releases/download/v5/mate-notification-theme-slate-5.tar.xz : 50a0098652937d235a58a4435cfff0700286616d178957509fbaee0583535dce
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : The Slate notification Daemon theme for MATE
description: |
    This provides a notification style identical to the Arc-styled Budgie Desktop notifications.
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - mate-notification-daemon
replaces   :
    - mate-notification-theme-solus
setup      : |
    %patch -p1 < $pkgfiles/0001-Check-for-a-hash-table-size-and-nullable-before-look.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    # Ensure upgrades don't break the existing configuration
    ln -sv libslate.so $installdir/%libdir%/mate-notification-daemon/engines/libsolus-mate-theme.so
